import type { Metadata } from "next";
import { Chivo } from "next/font/google";
import "./globals.css";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";

const chivo = Chivo({
  variable: "--font-chivo-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={chivo.className}>
        <AppRouterCacheProvider>{children}+ </AppRouterCacheProvider>
      </body>
    </html>
  );
}
